use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :wwelo, WweloWeb.Endpoint,
  https: [
    port: 4000,
    keyfile: "priv/server.key",
    certfile: "priv/server.pem"
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/.bin/webpack-dev-server",
      "--https",
      "--key",
      "../priv/server.key",
      "--cert",
      "../priv/server.pem",
      "--inline",
      "--colors",
      "--hot",
      "--stdin",
      "--host",
      "local.wwelo.com",
      "--port",
      "8080",
      "--public",
      "local.wwelo.com:8080",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :wwelo, WweloWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/wwelo_web/views/.*(ex)$},
      ~r{lib/wwelo_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n", level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :wwelo, Wwelo.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "wwelo_dev",
  hostname: "localhost",
  pool_size: 10

config :wwelo, :children, [Wwelo.Repo, WweloWeb.Endpoint]

# Pre-commit hooks
config :pre_commit,
  commands: ["format", "coveralls", "credo", "dialyzer", "js_pre_commits"],
  verbose: true
